---
version: '2.1'

services:
    # Apache Storm
    storm:
        image: fmantuano/apache-storm:develop
        container_name: storm
        mem_limit: 4g
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8000:8000"
        healthcheck:
            test: curl -fs http://localhost:8080/
        networks:
            - stormnet

networks:
    stormnet:
        driver: bridge
